# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|

  config.vm.define "kdc" do |kdc|
    kdc.vm.box = "ubuntu/xenial64"
    kdc.vm.hostname = "kdc.example.com"
    kdc.vm.network :forwarded_port, host: 8888, guest: 88, protocol: 'udp'
    kdc.vm.network :forwarded_port, host: 8888, guest: 88, protocol: 'tcp'
    kdc.vm.network :forwarded_port, host: 8749, guest: 8749
    kdc.vm.network :forwarded_port, host: 1389, guest: 389
    kdc.vm.network :forwarded_port, host: 1636, guest: 636
    kdc.vm.network "private_network", ip: "192.168.56.10"
    kdc.vm.provider "virtualbox" do |vb|
      vb.linked_clone = true
      vb.cpus = "1"
      vb.memory = "1024"
    end
    kdc.vm.provision "shell", path: "hostes.sh"
    kdc.vm.provision "shell", path: "ldap.sh"
    kdc.vm.provision "shell", path: "kerberos.sh"
  end
end
