
# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
    config.vm.box = "ubuntu/bionic64"
    config.vm.hostname = 'sp.logicalclocks.com'

    config.vm.network :forwarded_port, guest: 22, host: 10022, id: "ssh"
    # MySQL Server
    config.vm.network(:forwarded_port, {:guest=>3306, :host=>3306})
    # Hopsworks http
    config.vm.network(:forwarded_port, {:guest=>8080, :host=>8080})
    # Hopsworks https
    config.vm.network(:forwarded_port, {:guest=>8181, :host=>8181})
    # Glassfish admin UI
    config.vm.network(:forwarded_port, {:guest=>4848, :host=>4848})
    config.vm.provision "shell", path: "provision.sh"

    config.vm.provider :virtualbox do |v|
      v.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
      v.customize ["modifyvm", :id, "--memory", 4096]
      v.customize ["modifyvm", :id, "--cpus", "2"]
    end

end